#!/usr/bin/env bash
#creates the file containing its PID
echo $$ > /var/run/myscript.pid
trap 'echo Y U no love me?!' SIGNIT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
trap 'echo I hate the kill command; rm /var/run/myscript.pid; exit' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
