#!/usr/bin/env bash
#creates the file containing its PID
echo $$ > /var/run/myscript.pid
trap 'echo Y U no love me ?' SIGINT
trap 'rm $file; exit' SIGQUIT
trap 'echo I hate the kill command; rm $file; exit' SIGTERM
while :
do
echo "To infinity and beyond"
sleep 2
done
